[package]
name = "actix-starter"
version = "0.1.0"
authors = ["florianfelix <florianfelixmeyer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.0.2"